// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _traffic_decoder_HH_
#define _traffic_decoder_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct traffic_decoder : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<512> > raw_packet_tdata_V;
    sc_in< sc_lv<1> > raw_packet_tvalid_V;
    sc_out< sc_lv<1> > raw_packet_tready_V;
    sc_out< sc_lv<512> > decoded_packet_tdata_V;
    sc_out< sc_lv<64> > decoded_packet_tkeep_V;
    sc_out< sc_lv<1> > decoded_packet_tlast_V;
    sc_out< sc_lv<1> > decoded_packet_tvalid_V;
    sc_in< sc_lv<1> > decoded_packet_tready_V;


    // Module declarations
    traffic_decoder(sc_module_name name);
    SC_HAS_PROCESS(traffic_decoder);

    ~traffic_decoder();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<512> > meta_V;
    sc_signal< sc_lv<6> > meta_count_V;
    sc_signal< sc_lv<512> > r_V_1_fu_890_p3;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<1> > ret_V_fu_872_p2;
    sc_signal< sc_lv<6> > add_ln700_fu_904_p2;
    sc_signal< sc_lv<7> > p_Result_2_fu_267_p4;
    sc_signal< sc_lv<2> > tmp_2_fu_471_p4;
    sc_signal< sc_lv<3> > tmp_3_fu_577_p4;
    sc_signal< sc_lv<4> > tmp_4_fu_635_p4;
    sc_signal< sc_lv<5> > tmp_5_fu_669_p4;
    sc_signal< sc_lv<6> > tmp_6_fu_691_p4;
    sc_signal< sc_lv<1> > icmp_ln17_fu_707_p2;
    sc_signal< sc_lv<1> > icmp_ln895_61_fu_701_p2;
    sc_signal< sc_lv<1> > icmp_ln895_60_fu_685_p2;
    sc_signal< sc_lv<1> > icmp_ln895_59_fu_679_p2;
    sc_signal< sc_lv<1> > icmp_ln895_58_fu_663_p2;
    sc_signal< sc_lv<1> > icmp_ln895_57_fu_657_p2;
    sc_signal< sc_lv<1> > icmp_ln895_56_fu_651_p2;
    sc_signal< sc_lv<1> > icmp_ln895_55_fu_645_p2;
    sc_signal< sc_lv<1> > icmp_ln895_54_fu_629_p2;
    sc_signal< sc_lv<1> > icmp_ln895_53_fu_623_p2;
    sc_signal< sc_lv<1> > icmp_ln895_52_fu_617_p2;
    sc_signal< sc_lv<1> > icmp_ln895_51_fu_611_p2;
    sc_signal< sc_lv<1> > icmp_ln895_50_fu_605_p2;
    sc_signal< sc_lv<1> > icmp_ln895_49_fu_599_p2;
    sc_signal< sc_lv<1> > icmp_ln895_48_fu_593_p2;
    sc_signal< sc_lv<1> > icmp_ln895_47_fu_587_p2;
    sc_signal< sc_lv<1> > icmp_ln895_46_fu_571_p2;
    sc_signal< sc_lv<1> > icmp_ln895_45_fu_565_p2;
    sc_signal< sc_lv<1> > icmp_ln895_44_fu_559_p2;
    sc_signal< sc_lv<1> > icmp_ln895_43_fu_553_p2;
    sc_signal< sc_lv<1> > icmp_ln895_42_fu_547_p2;
    sc_signal< sc_lv<1> > icmp_ln895_41_fu_541_p2;
    sc_signal< sc_lv<1> > icmp_ln895_40_fu_535_p2;
    sc_signal< sc_lv<1> > icmp_ln895_39_fu_529_p2;
    sc_signal< sc_lv<1> > icmp_ln895_38_fu_523_p2;
    sc_signal< sc_lv<1> > icmp_ln895_37_fu_517_p2;
    sc_signal< sc_lv<1> > icmp_ln895_36_fu_511_p2;
    sc_signal< sc_lv<1> > icmp_ln895_35_fu_505_p2;
    sc_signal< sc_lv<1> > icmp_ln895_34_fu_499_p2;
    sc_signal< sc_lv<1> > icmp_ln895_33_fu_493_p2;
    sc_signal< sc_lv<1> > icmp_ln895_32_fu_487_p2;
    sc_signal< sc_lv<1> > icmp_ln895_31_fu_481_p2;
    sc_signal< sc_lv<1> > icmp_ln895_30_fu_465_p2;
    sc_signal< sc_lv<1> > icmp_ln895_29_fu_459_p2;
    sc_signal< sc_lv<1> > icmp_ln895_28_fu_453_p2;
    sc_signal< sc_lv<1> > icmp_ln895_27_fu_447_p2;
    sc_signal< sc_lv<1> > icmp_ln895_26_fu_441_p2;
    sc_signal< sc_lv<1> > icmp_ln895_25_fu_435_p2;
    sc_signal< sc_lv<1> > icmp_ln895_24_fu_429_p2;
    sc_signal< sc_lv<1> > icmp_ln895_23_fu_423_p2;
    sc_signal< sc_lv<1> > icmp_ln895_22_fu_417_p2;
    sc_signal< sc_lv<1> > icmp_ln895_21_fu_411_p2;
    sc_signal< sc_lv<1> > icmp_ln895_20_fu_405_p2;
    sc_signal< sc_lv<1> > icmp_ln895_19_fu_399_p2;
    sc_signal< sc_lv<1> > icmp_ln895_18_fu_393_p2;
    sc_signal< sc_lv<1> > icmp_ln895_17_fu_387_p2;
    sc_signal< sc_lv<1> > icmp_ln895_16_fu_381_p2;
    sc_signal< sc_lv<1> > icmp_ln895_15_fu_375_p2;
    sc_signal< sc_lv<1> > icmp_ln895_14_fu_369_p2;
    sc_signal< sc_lv<1> > icmp_ln895_13_fu_363_p2;
    sc_signal< sc_lv<1> > icmp_ln895_12_fu_357_p2;
    sc_signal< sc_lv<1> > icmp_ln895_11_fu_351_p2;
    sc_signal< sc_lv<1> > icmp_ln895_10_fu_345_p2;
    sc_signal< sc_lv<1> > icmp_ln895_9_fu_339_p2;
    sc_signal< sc_lv<1> > icmp_ln895_8_fu_333_p2;
    sc_signal< sc_lv<1> > icmp_ln895_7_fu_327_p2;
    sc_signal< sc_lv<1> > icmp_ln895_6_fu_321_p2;
    sc_signal< sc_lv<1> > icmp_ln895_5_fu_315_p2;
    sc_signal< sc_lv<1> > icmp_ln895_4_fu_309_p2;
    sc_signal< sc_lv<1> > icmp_ln895_3_fu_303_p2;
    sc_signal< sc_lv<1> > icmp_ln895_2_fu_297_p2;
    sc_signal< sc_lv<1> > icmp_ln895_1_fu_291_p2;
    sc_signal< sc_lv<1> > icmp_ln895_fu_285_p2;
    sc_signal< sc_lv<1> > tmp_1_fu_277_p3;
    sc_signal< sc_lv<1> > icmp_ln883_fu_859_p2;
    sc_signal< sc_lv<1> > icmp_ln879_fu_878_p2;
    sc_signal< sc_lv<512> > r_V_fu_884_p2;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<512> ap_const_lv512_lc_1;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1F9;
    static const sc_lv<32> ap_const_lv32_1FF;
    static const sc_lv<7> ap_const_lv7_3E;
    static const sc_lv<7> ap_const_lv7_3D;
    static const sc_lv<7> ap_const_lv7_3C;
    static const sc_lv<7> ap_const_lv7_3B;
    static const sc_lv<7> ap_const_lv7_3A;
    static const sc_lv<7> ap_const_lv7_39;
    static const sc_lv<7> ap_const_lv7_38;
    static const sc_lv<7> ap_const_lv7_37;
    static const sc_lv<7> ap_const_lv7_36;
    static const sc_lv<7> ap_const_lv7_35;
    static const sc_lv<7> ap_const_lv7_34;
    static const sc_lv<7> ap_const_lv7_33;
    static const sc_lv<7> ap_const_lv7_32;
    static const sc_lv<7> ap_const_lv7_31;
    static const sc_lv<7> ap_const_lv7_30;
    static const sc_lv<7> ap_const_lv7_2F;
    static const sc_lv<7> ap_const_lv7_2E;
    static const sc_lv<7> ap_const_lv7_2D;
    static const sc_lv<7> ap_const_lv7_2C;
    static const sc_lv<7> ap_const_lv7_2B;
    static const sc_lv<7> ap_const_lv7_2A;
    static const sc_lv<7> ap_const_lv7_29;
    static const sc_lv<7> ap_const_lv7_28;
    static const sc_lv<7> ap_const_lv7_27;
    static const sc_lv<7> ap_const_lv7_26;
    static const sc_lv<7> ap_const_lv7_25;
    static const sc_lv<7> ap_const_lv7_24;
    static const sc_lv<7> ap_const_lv7_23;
    static const sc_lv<7> ap_const_lv7_22;
    static const sc_lv<7> ap_const_lv7_21;
    static const sc_lv<7> ap_const_lv7_20;
    static const sc_lv<32> ap_const_lv32_1FE;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<7> ap_const_lv7_1E;
    static const sc_lv<7> ap_const_lv7_1D;
    static const sc_lv<7> ap_const_lv7_1C;
    static const sc_lv<7> ap_const_lv7_1B;
    static const sc_lv<7> ap_const_lv7_1A;
    static const sc_lv<7> ap_const_lv7_19;
    static const sc_lv<7> ap_const_lv7_18;
    static const sc_lv<7> ap_const_lv7_17;
    static const sc_lv<7> ap_const_lv7_16;
    static const sc_lv<7> ap_const_lv7_15;
    static const sc_lv<7> ap_const_lv7_14;
    static const sc_lv<7> ap_const_lv7_13;
    static const sc_lv<7> ap_const_lv7_12;
    static const sc_lv<7> ap_const_lv7_11;
    static const sc_lv<7> ap_const_lv7_10;
    static const sc_lv<32> ap_const_lv32_1FD;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<7> ap_const_lv7_E;
    static const sc_lv<7> ap_const_lv7_D;
    static const sc_lv<7> ap_const_lv7_C;
    static const sc_lv<7> ap_const_lv7_B;
    static const sc_lv<7> ap_const_lv7_A;
    static const sc_lv<7> ap_const_lv7_9;
    static const sc_lv<7> ap_const_lv7_8;
    static const sc_lv<32> ap_const_lv32_1FC;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<7> ap_const_lv7_6;
    static const sc_lv<7> ap_const_lv7_5;
    static const sc_lv<7> ap_const_lv7_4;
    static const sc_lv<32> ap_const_lv32_1FB;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<7> ap_const_lv7_2;
    static const sc_lv<32> ap_const_lv32_1FA;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_1F8;
    static const sc_lv<512> ap_const_lv512_lc_2;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln700_fu_904_p2();
    void thread_ap_CS_fsm_state1();
    void thread_decoded_packet_tdata_V();
    void thread_decoded_packet_tkeep_V();
    void thread_decoded_packet_tlast_V();
    void thread_decoded_packet_tvalid_V();
    void thread_icmp_ln17_fu_707_p2();
    void thread_icmp_ln879_fu_878_p2();
    void thread_icmp_ln883_fu_859_p2();
    void thread_icmp_ln895_10_fu_345_p2();
    void thread_icmp_ln895_11_fu_351_p2();
    void thread_icmp_ln895_12_fu_357_p2();
    void thread_icmp_ln895_13_fu_363_p2();
    void thread_icmp_ln895_14_fu_369_p2();
    void thread_icmp_ln895_15_fu_375_p2();
    void thread_icmp_ln895_16_fu_381_p2();
    void thread_icmp_ln895_17_fu_387_p2();
    void thread_icmp_ln895_18_fu_393_p2();
    void thread_icmp_ln895_19_fu_399_p2();
    void thread_icmp_ln895_1_fu_291_p2();
    void thread_icmp_ln895_20_fu_405_p2();
    void thread_icmp_ln895_21_fu_411_p2();
    void thread_icmp_ln895_22_fu_417_p2();
    void thread_icmp_ln895_23_fu_423_p2();
    void thread_icmp_ln895_24_fu_429_p2();
    void thread_icmp_ln895_25_fu_435_p2();
    void thread_icmp_ln895_26_fu_441_p2();
    void thread_icmp_ln895_27_fu_447_p2();
    void thread_icmp_ln895_28_fu_453_p2();
    void thread_icmp_ln895_29_fu_459_p2();
    void thread_icmp_ln895_2_fu_297_p2();
    void thread_icmp_ln895_30_fu_465_p2();
    void thread_icmp_ln895_31_fu_481_p2();
    void thread_icmp_ln895_32_fu_487_p2();
    void thread_icmp_ln895_33_fu_493_p2();
    void thread_icmp_ln895_34_fu_499_p2();
    void thread_icmp_ln895_35_fu_505_p2();
    void thread_icmp_ln895_36_fu_511_p2();
    void thread_icmp_ln895_37_fu_517_p2();
    void thread_icmp_ln895_38_fu_523_p2();
    void thread_icmp_ln895_39_fu_529_p2();
    void thread_icmp_ln895_3_fu_303_p2();
    void thread_icmp_ln895_40_fu_535_p2();
    void thread_icmp_ln895_41_fu_541_p2();
    void thread_icmp_ln895_42_fu_547_p2();
    void thread_icmp_ln895_43_fu_553_p2();
    void thread_icmp_ln895_44_fu_559_p2();
    void thread_icmp_ln895_45_fu_565_p2();
    void thread_icmp_ln895_46_fu_571_p2();
    void thread_icmp_ln895_47_fu_587_p2();
    void thread_icmp_ln895_48_fu_593_p2();
    void thread_icmp_ln895_49_fu_599_p2();
    void thread_icmp_ln895_4_fu_309_p2();
    void thread_icmp_ln895_50_fu_605_p2();
    void thread_icmp_ln895_51_fu_611_p2();
    void thread_icmp_ln895_52_fu_617_p2();
    void thread_icmp_ln895_53_fu_623_p2();
    void thread_icmp_ln895_54_fu_629_p2();
    void thread_icmp_ln895_55_fu_645_p2();
    void thread_icmp_ln895_56_fu_651_p2();
    void thread_icmp_ln895_57_fu_657_p2();
    void thread_icmp_ln895_58_fu_663_p2();
    void thread_icmp_ln895_59_fu_679_p2();
    void thread_icmp_ln895_5_fu_315_p2();
    void thread_icmp_ln895_60_fu_685_p2();
    void thread_icmp_ln895_61_fu_701_p2();
    void thread_icmp_ln895_6_fu_321_p2();
    void thread_icmp_ln895_7_fu_327_p2();
    void thread_icmp_ln895_8_fu_333_p2();
    void thread_icmp_ln895_9_fu_339_p2();
    void thread_icmp_ln895_fu_285_p2();
    void thread_p_Result_2_fu_267_p4();
    void thread_r_V_1_fu_890_p3();
    void thread_r_V_fu_884_p2();
    void thread_raw_packet_tready_V();
    void thread_ret_V_fu_872_p2();
    void thread_tmp_1_fu_277_p3();
    void thread_tmp_2_fu_471_p4();
    void thread_tmp_3_fu_577_p4();
    void thread_tmp_4_fu_635_p4();
    void thread_tmp_5_fu_669_p4();
    void thread_tmp_6_fu_691_p4();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
