#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("start_V", 1, hls_out, 13, "ap_none", "out_data", 1),
	Port_Property("rst_V", 1, hls_out, 14, "ap_none", "out_data", 1),
	Port_Property("transfer_length_V", 64, hls_out, 15, "ap_none", "out_data", 1),
	Port_Property("mismatch_V", 1, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("tx_timeElapse_V", 32, hls_in, 17, "ap_none", "in_data", 1),
	Port_Property("rx_timeElapse_V", 32, hls_in, 18, "ap_none", "in_data", 1),
	Port_Property("tx_timestamp_sum_V", 64, hls_in, 19, "ap_none", "in_data", 1),
	Port_Property("rx_timestamp_sum_V", 64, hls_in, 20, "ap_none", "in_data", 1),
	Port_Property("pkt_cnt_tx_V", 32, hls_in, 21, "ap_none", "in_data", 1),
	Port_Property("pkt_cnt_rx_V", 32, hls_in, 22, "ap_none", "in_data", 1),
	Port_Property("s_axi_AXILiteS_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_AWADDR", 7, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_ARADDR", 7, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "sw_interface";
