#include "user_def.h"
/* architecture related configurations */
#ifndef PAGE_SIZE
	#define PAGE_SIZE 4096
#endif

#ifndef FPGA_DDR_ADDR_RANGE
	#define FPGA_DDR_ADDR_RANGE 0x400000000 //16GB
#endif

#ifndef DMA_BUFFER_SIZE
	#define DMA_BUFFER_SIZE 64*1024*1024 //64MB
#endif

#define DMA_BUFFER_SIZE_IN_PAGE DMA_BUFFER_SIZE/PAGE_SIZE

/* Traffic generator offset */
#define START			TRAFFIC_GEN_OFFSET+0x10
#define RST			TRAFFIC_GEN_OFFSET+0x18
#define OFFSET_LOW		TRAFFIC_GEN_OFFSET+0x20
#define OFFSET_HIGH		TRAFFIC_GEN_OFFSET+0x28
#define LEN_LOW			TRAFFIC_GEN_OFFSET+0x30
#define LEN_HIGH		TRAFFIC_GEN_OFFSET+0x38
#define MISMATCH		TRAFFIC_GEN_OFFSET+0x40
#define TX_TIMEELAPSE		TRAFFIC_GEN_OFFSET+0x48
#define RX_TIMEELAPSE		TRAFFIC_GEN_OFFSET+0x50
#define TX_TIMESTAMP_SUM_LOW	TRAFFIC_GEN_OFFSET+0x58
#define TX_TIMESTAMP_SUM_HIGH	TRAFFIC_GEN_OFFSET+0x60
#define RX_TIMESTAMP_SUM_LOW	TRAFFIC_GEN_OFFSET+0x68
#define RX_TIMESTAMP_SUM_HIGH	TRAFFIC_GEN_OFFSET+0x70
#define PKT_CNT_TX		TRAFFIC_GEN_OFFSET+0x78
#define PKT_CNT_RX		TRAFFIC_GEN_OFFSET+0x80
