// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="datamover_controller,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu19eg-ffvc1760-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.117500,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=220,HLS_SYN_LUT=230,HLS_VERSION=2019_1}" *)

module datamover_controller (
        ap_clk,
        ap_rst,
        start_V,
        length_V,
        m_axis_tdata_V,
        m_axis_tvalid_V,
        m_axis_tready_V
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input  [0:0] start_V;
input  [63:0] length_V;
output  [103:0] m_axis_tdata_V;
output  [0:0] m_axis_tvalid_V;
input  [0:0] m_axis_tready_V;

reg   [103:0] m_axis_reg_tdata_V;
reg   [0:0] m_axis_reg_tvalid_V;
reg   [0:0] start_reg_V;
reg   [0:0] core_on_V;
reg   [63:0] curr_addr_V;
reg   [63:0] length_reg_V;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] ret_V_fu_120_p2;
wire   [0:0] core_on_V_load_load_fu_126_p1;
wire   [103:0] p_Result_s_fu_168_p5;
wire   [0:0] m_axis_tready_V_read_read_fu_68_p2;
wire   [0:0] icmp_ln895_fu_146_p2;
wire   [63:0] add_ln700_fu_210_p2;
wire   [63:0] add_ln701_fu_198_p2;
wire   [0:0] lhs_V_fu_114_p2;
wire   [22:0] trunc_ln681_fu_152_p1;
wire   [22:0] byte_to_transfer_V_fu_156_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_condition_52;
reg    ap_condition_60;

// power-on initialization
initial begin
#0 m_axis_reg_tdata_V = 104'd0;
#0 m_axis_reg_tvalid_V = 1'd0;
#0 start_reg_V = 1'd0;
#0 core_on_V = 1'd0;
#0 curr_addr_V = 64'd0;
#0 length_reg_V = 64'd0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        core_on_V <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            if ((ret_V_fu_120_p2 == 1'd1)) begin
                core_on_V <= 1'd1;
            end else if ((1'b1 == ap_condition_52)) begin
                core_on_V <= 1'd0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        curr_addr_V <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            if ((ret_V_fu_120_p2 == 1'd1)) begin
                curr_addr_V <= 64'd0;
            end else if ((1'b1 == ap_condition_60)) begin
                curr_addr_V <= add_ln700_fu_210_p2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        length_reg_V <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            if ((ret_V_fu_120_p2 == 1'd1)) begin
                length_reg_V <= length_V;
            end else if ((1'b1 == ap_condition_60)) begin
                length_reg_V <= add_ln701_fu_198_p2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                m_axis_reg_tdata_V[0] <= 1'b0;
        m_axis_reg_tdata_V[1] <= 1'b0;
        m_axis_reg_tdata_V[2] <= 1'b0;
        m_axis_reg_tdata_V[3] <= 1'b0;
        m_axis_reg_tdata_V[4] <= 1'b0;
        m_axis_reg_tdata_V[5] <= 1'b0;
        m_axis_reg_tdata_V[6] <= 1'b0;
        m_axis_reg_tdata_V[7] <= 1'b0;
        m_axis_reg_tdata_V[8] <= 1'b0;
        m_axis_reg_tdata_V[9] <= 1'b0;
        m_axis_reg_tdata_V[10] <= 1'b0;
        m_axis_reg_tdata_V[11] <= 1'b0;
        m_axis_reg_tdata_V[12] <= 1'b0;
        m_axis_reg_tdata_V[13] <= 1'b0;
        m_axis_reg_tdata_V[14] <= 1'b0;
        m_axis_reg_tdata_V[15] <= 1'b0;
        m_axis_reg_tdata_V[16] <= 1'b0;
        m_axis_reg_tdata_V[17] <= 1'b0;
        m_axis_reg_tdata_V[18] <= 1'b0;
        m_axis_reg_tdata_V[19] <= 1'b0;
        m_axis_reg_tdata_V[20] <= 1'b0;
        m_axis_reg_tdata_V[21] <= 1'b0;
        m_axis_reg_tdata_V[22] <= 1'b0;
        m_axis_reg_tdata_V[23] <= 1'b0;
        m_axis_reg_tdata_V[32] <= 1'b0;
        m_axis_reg_tdata_V[33] <= 1'b0;
        m_axis_reg_tdata_V[34] <= 1'b0;
        m_axis_reg_tdata_V[35] <= 1'b0;
        m_axis_reg_tdata_V[36] <= 1'b0;
        m_axis_reg_tdata_V[37] <= 1'b0;
        m_axis_reg_tdata_V[38] <= 1'b0;
        m_axis_reg_tdata_V[39] <= 1'b0;
        m_axis_reg_tdata_V[40] <= 1'b0;
        m_axis_reg_tdata_V[41] <= 1'b0;
        m_axis_reg_tdata_V[42] <= 1'b0;
        m_axis_reg_tdata_V[43] <= 1'b0;
        m_axis_reg_tdata_V[44] <= 1'b0;
        m_axis_reg_tdata_V[45] <= 1'b0;
        m_axis_reg_tdata_V[46] <= 1'b0;
        m_axis_reg_tdata_V[47] <= 1'b0;
        m_axis_reg_tdata_V[48] <= 1'b0;
        m_axis_reg_tdata_V[49] <= 1'b0;
        m_axis_reg_tdata_V[50] <= 1'b0;
        m_axis_reg_tdata_V[51] <= 1'b0;
        m_axis_reg_tdata_V[52] <= 1'b0;
        m_axis_reg_tdata_V[53] <= 1'b0;
        m_axis_reg_tdata_V[54] <= 1'b0;
        m_axis_reg_tdata_V[55] <= 1'b0;
        m_axis_reg_tdata_V[56] <= 1'b0;
        m_axis_reg_tdata_V[57] <= 1'b0;
        m_axis_reg_tdata_V[58] <= 1'b0;
        m_axis_reg_tdata_V[59] <= 1'b0;
        m_axis_reg_tdata_V[60] <= 1'b0;
        m_axis_reg_tdata_V[61] <= 1'b0;
        m_axis_reg_tdata_V[62] <= 1'b0;
        m_axis_reg_tdata_V[63] <= 1'b0;
        m_axis_reg_tdata_V[64] <= 1'b0;
        m_axis_reg_tdata_V[65] <= 1'b0;
        m_axis_reg_tdata_V[66] <= 1'b0;
        m_axis_reg_tdata_V[67] <= 1'b0;
        m_axis_reg_tdata_V[68] <= 1'b0;
        m_axis_reg_tdata_V[69] <= 1'b0;
        m_axis_reg_tdata_V[70] <= 1'b0;
        m_axis_reg_tdata_V[71] <= 1'b0;
        m_axis_reg_tdata_V[72] <= 1'b0;
        m_axis_reg_tdata_V[73] <= 1'b0;
        m_axis_reg_tdata_V[74] <= 1'b0;
        m_axis_reg_tdata_V[75] <= 1'b0;
        m_axis_reg_tdata_V[76] <= 1'b0;
        m_axis_reg_tdata_V[77] <= 1'b0;
        m_axis_reg_tdata_V[78] <= 1'b0;
        m_axis_reg_tdata_V[79] <= 1'b0;
        m_axis_reg_tdata_V[80] <= 1'b0;
        m_axis_reg_tdata_V[81] <= 1'b0;
        m_axis_reg_tdata_V[82] <= 1'b0;
        m_axis_reg_tdata_V[83] <= 1'b0;
        m_axis_reg_tdata_V[84] <= 1'b0;
        m_axis_reg_tdata_V[85] <= 1'b0;
        m_axis_reg_tdata_V[86] <= 1'b0;
        m_axis_reg_tdata_V[87] <= 1'b0;
        m_axis_reg_tdata_V[88] <= 1'b0;
        m_axis_reg_tdata_V[89] <= 1'b0;
        m_axis_reg_tdata_V[90] <= 1'b0;
        m_axis_reg_tdata_V[91] <= 1'b0;
        m_axis_reg_tdata_V[92] <= 1'b0;
        m_axis_reg_tdata_V[93] <= 1'b0;
        m_axis_reg_tdata_V[94] <= 1'b0;
        m_axis_reg_tdata_V[95] <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ret_V_fu_120_p2 == 1'd0))) begin
            if (((m_axis_tready_V_read_read_fu_68_p2 == 1'd1) & (core_on_V_load_load_fu_126_p1 == 1'd1))) begin
                                m_axis_reg_tdata_V[23 : 0] <= p_Result_s_fu_168_p5[23 : 0];
                m_axis_reg_tdata_V[95 : 32] <= p_Result_s_fu_168_p5[95 : 32];
            end else if ((core_on_V_load_load_fu_126_p1 == 1'd0)) begin
                                m_axis_reg_tdata_V[0] <= 1'b0;
                m_axis_reg_tdata_V[1] <= 1'b0;
                m_axis_reg_tdata_V[2] <= 1'b0;
                m_axis_reg_tdata_V[3] <= 1'b0;
                m_axis_reg_tdata_V[4] <= 1'b0;
                m_axis_reg_tdata_V[5] <= 1'b0;
                m_axis_reg_tdata_V[6] <= 1'b0;
                m_axis_reg_tdata_V[7] <= 1'b0;
                m_axis_reg_tdata_V[8] <= 1'b0;
                m_axis_reg_tdata_V[9] <= 1'b0;
                m_axis_reg_tdata_V[10] <= 1'b0;
                m_axis_reg_tdata_V[11] <= 1'b0;
                m_axis_reg_tdata_V[12] <= 1'b0;
                m_axis_reg_tdata_V[13] <= 1'b0;
                m_axis_reg_tdata_V[14] <= 1'b0;
                m_axis_reg_tdata_V[15] <= 1'b0;
                m_axis_reg_tdata_V[16] <= 1'b0;
                m_axis_reg_tdata_V[17] <= 1'b0;
                m_axis_reg_tdata_V[18] <= 1'b0;
                m_axis_reg_tdata_V[19] <= 1'b0;
                m_axis_reg_tdata_V[20] <= 1'b0;
                m_axis_reg_tdata_V[21] <= 1'b0;
                m_axis_reg_tdata_V[22] <= 1'b0;
                m_axis_reg_tdata_V[23] <= 1'b0;
                m_axis_reg_tdata_V[32] <= 1'b0;
                m_axis_reg_tdata_V[33] <= 1'b0;
                m_axis_reg_tdata_V[34] <= 1'b0;
                m_axis_reg_tdata_V[35] <= 1'b0;
                m_axis_reg_tdata_V[36] <= 1'b0;
                m_axis_reg_tdata_V[37] <= 1'b0;
                m_axis_reg_tdata_V[38] <= 1'b0;
                m_axis_reg_tdata_V[39] <= 1'b0;
                m_axis_reg_tdata_V[40] <= 1'b0;
                m_axis_reg_tdata_V[41] <= 1'b0;
                m_axis_reg_tdata_V[42] <= 1'b0;
                m_axis_reg_tdata_V[43] <= 1'b0;
                m_axis_reg_tdata_V[44] <= 1'b0;
                m_axis_reg_tdata_V[45] <= 1'b0;
                m_axis_reg_tdata_V[46] <= 1'b0;
                m_axis_reg_tdata_V[47] <= 1'b0;
                m_axis_reg_tdata_V[48] <= 1'b0;
                m_axis_reg_tdata_V[49] <= 1'b0;
                m_axis_reg_tdata_V[50] <= 1'b0;
                m_axis_reg_tdata_V[51] <= 1'b0;
                m_axis_reg_tdata_V[52] <= 1'b0;
                m_axis_reg_tdata_V[53] <= 1'b0;
                m_axis_reg_tdata_V[54] <= 1'b0;
                m_axis_reg_tdata_V[55] <= 1'b0;
                m_axis_reg_tdata_V[56] <= 1'b0;
                m_axis_reg_tdata_V[57] <= 1'b0;
                m_axis_reg_tdata_V[58] <= 1'b0;
                m_axis_reg_tdata_V[59] <= 1'b0;
                m_axis_reg_tdata_V[60] <= 1'b0;
                m_axis_reg_tdata_V[61] <= 1'b0;
                m_axis_reg_tdata_V[62] <= 1'b0;
                m_axis_reg_tdata_V[63] <= 1'b0;
                m_axis_reg_tdata_V[64] <= 1'b0;
                m_axis_reg_tdata_V[65] <= 1'b0;
                m_axis_reg_tdata_V[66] <= 1'b0;
                m_axis_reg_tdata_V[67] <= 1'b0;
                m_axis_reg_tdata_V[68] <= 1'b0;
                m_axis_reg_tdata_V[69] <= 1'b0;
                m_axis_reg_tdata_V[70] <= 1'b0;
                m_axis_reg_tdata_V[71] <= 1'b0;
                m_axis_reg_tdata_V[72] <= 1'b0;
                m_axis_reg_tdata_V[73] <= 1'b0;
                m_axis_reg_tdata_V[74] <= 1'b0;
                m_axis_reg_tdata_V[75] <= 1'b0;
                m_axis_reg_tdata_V[76] <= 1'b0;
                m_axis_reg_tdata_V[77] <= 1'b0;
                m_axis_reg_tdata_V[78] <= 1'b0;
                m_axis_reg_tdata_V[79] <= 1'b0;
                m_axis_reg_tdata_V[80] <= 1'b0;
                m_axis_reg_tdata_V[81] <= 1'b0;
                m_axis_reg_tdata_V[82] <= 1'b0;
                m_axis_reg_tdata_V[83] <= 1'b0;
                m_axis_reg_tdata_V[84] <= 1'b0;
                m_axis_reg_tdata_V[85] <= 1'b0;
                m_axis_reg_tdata_V[86] <= 1'b0;
                m_axis_reg_tdata_V[87] <= 1'b0;
                m_axis_reg_tdata_V[88] <= 1'b0;
                m_axis_reg_tdata_V[89] <= 1'b0;
                m_axis_reg_tdata_V[90] <= 1'b0;
                m_axis_reg_tdata_V[91] <= 1'b0;
                m_axis_reg_tdata_V[92] <= 1'b0;
                m_axis_reg_tdata_V[93] <= 1'b0;
                m_axis_reg_tdata_V[94] <= 1'b0;
                m_axis_reg_tdata_V[95] <= 1'b0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        m_axis_reg_tvalid_V <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ret_V_fu_120_p2 == 1'd0))) begin
            if (((m_axis_tready_V_read_read_fu_68_p2 == 1'd1) & (core_on_V_load_load_fu_126_p1 == 1'd1))) begin
                m_axis_reg_tvalid_V <= 1'd1;
            end else if ((core_on_V_load_load_fu_126_p1 == 1'd0)) begin
                m_axis_reg_tvalid_V <= 1'd0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_reg_V <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            start_reg_V <= start_V;
        end
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln700_fu_210_p2 = (curr_addr_V + 64'd4194304);

assign add_ln701_fu_198_p2 = ($signed(length_reg_V) + $signed(64'd18446744073705357312));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_condition_52 = ((m_axis_tready_V_read_read_fu_68_p2 == 1'd1) & (core_on_V_load_load_fu_126_p1 == 1'd1) & (icmp_ln895_fu_146_p2 == 1'd0) & (ret_V_fu_120_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_60 = ((icmp_ln895_fu_146_p2 == 1'd1) & (m_axis_tready_V_read_read_fu_68_p2 == 1'd1) & (core_on_V_load_load_fu_126_p1 == 1'd1) & (ret_V_fu_120_p2 == 1'd0));
end

assign byte_to_transfer_V_fu_156_p3 = ((icmp_ln895_fu_146_p2[0:0] === 1'b1) ? 23'd4194304 : trunc_ln681_fu_152_p1);

assign core_on_V_load_load_fu_126_p1 = core_on_V;

assign icmp_ln895_fu_146_p2 = ((length_reg_V > 64'd4194304) ? 1'b1 : 1'b0);

assign lhs_V_fu_114_p2 = (start_reg_V ^ 1'd1);

assign m_axis_tdata_V = m_axis_reg_tdata_V;

assign m_axis_tready_V_read_read_fu_68_p2 = m_axis_tready_V;

assign m_axis_tvalid_V = m_axis_reg_tvalid_V;

assign p_Result_s_fu_168_p5 = {{{{{{8'd0}, {curr_addr_V}}}, {9'd1}}}, {byte_to_transfer_V_fu_156_p3}};

assign ret_V_fu_120_p2 = (start_V & lhs_V_fu_114_p2);

assign trunc_ln681_fu_152_p1 = length_reg_V[22:0];

always @ (posedge ap_clk) begin
    m_axis_reg_tdata_V[31:24] <= 8'b00000000;
    m_axis_reg_tdata_V[103:96] <= 8'b00000000;
end

endmodule //datamover_controller
