// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sw_interface.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int sw_interface::C_S_AXI_DATA_WIDTH = "100000";
const sc_logic sw_interface::ap_const_logic_1 = sc_dt::Log_1;
const bool sw_interface::ap_const_boolean_1 = true;
const sc_logic sw_interface::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<32> sw_interface::ap_const_lv32_20 = "100000";
const sc_lv<32> sw_interface::ap_const_lv32_3F = "111111";

sw_interface::sw_interface(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sw_interface_AXILiteS_s_axi_U = new sw_interface_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("sw_interface_AXILiteS_s_axi_U");
    sw_interface_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    sw_interface_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    sw_interface_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    sw_interface_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    sw_interface_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    sw_interface_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    sw_interface_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    sw_interface_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    sw_interface_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    sw_interface_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    sw_interface_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    sw_interface_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    sw_interface_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    sw_interface_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    sw_interface_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    sw_interface_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    sw_interface_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    sw_interface_AXILiteS_s_axi_U->ACLK(ap_clk);
    sw_interface_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    sw_interface_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    sw_interface_AXILiteS_s_axi_U->axil_start_V(axil_start_V);
    sw_interface_AXILiteS_s_axi_U->axil_rst_V(axil_rst_V);
    sw_interface_AXILiteS_s_axi_U->axil_len_low_V(axil_len_low_V);
    sw_interface_AXILiteS_s_axi_U->axil_len_high_V(axil_len_high_V);
    sw_interface_AXILiteS_s_axi_U->axil_mismatch_V(axil_mismatch_V);
    sw_interface_AXILiteS_s_axi_U->axil_mismatch_V_ap_vld(axil_mismatch_V_ap_vld);
    sw_interface_AXILiteS_s_axi_U->axil_tx_timeElapse_V(tx_timeElapse_V);
    sw_interface_AXILiteS_s_axi_U->axil_tx_timeElapse_V_ap_vld(axil_tx_timeElapse_V_ap_vld);
    sw_interface_AXILiteS_s_axi_U->axil_rx_timeElapse_V(rx_timeElapse_V);
    sw_interface_AXILiteS_s_axi_U->axil_rx_timeElapse_V_ap_vld(axil_rx_timeElapse_V_ap_vld);
    sw_interface_AXILiteS_s_axi_U->axil_tx_timestamp_sum_low_V(axil_tx_timestamp_sum_low_V);
    sw_interface_AXILiteS_s_axi_U->axil_tx_timestamp_sum_low_V_ap_vld(axil_tx_timestamp_sum_low_V_ap_vld);
    sw_interface_AXILiteS_s_axi_U->axil_tx_timestamp_sum_high_V(axil_tx_timestamp_sum_high_V);
    sw_interface_AXILiteS_s_axi_U->axil_tx_timestamp_sum_high_V_ap_vld(axil_tx_timestamp_sum_high_V_ap_vld);
    sw_interface_AXILiteS_s_axi_U->axil_rx_timestamp_sum_low_V(axil_rx_timestamp_sum_low_V);
    sw_interface_AXILiteS_s_axi_U->axil_rx_timestamp_sum_low_V_ap_vld(axil_rx_timestamp_sum_low_V_ap_vld);
    sw_interface_AXILiteS_s_axi_U->axil_rx_timestamp_sum_high_V(axil_rx_timestamp_sum_high_V);
    sw_interface_AXILiteS_s_axi_U->axil_rx_timestamp_sum_high_V_ap_vld(axil_rx_timestamp_sum_high_V_ap_vld);
    sw_interface_AXILiteS_s_axi_U->axil_pkt_cnt_tx_V(pkt_cnt_tx_V);
    sw_interface_AXILiteS_s_axi_U->axil_pkt_cnt_tx_V_ap_vld(axil_pkt_cnt_tx_V_ap_vld);
    sw_interface_AXILiteS_s_axi_U->axil_pkt_cnt_rx_V(pkt_cnt_rx_V);
    sw_interface_AXILiteS_s_axi_U->axil_pkt_cnt_rx_V_ap_vld(axil_pkt_cnt_rx_V_ap_vld);

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_axil_mismatch_V);
    sensitive << ( mismatch_V );

    SC_METHOD(thread_axil_mismatch_V_ap_vld);

    SC_METHOD(thread_axil_pkt_cnt_rx_V_ap_vld);

    SC_METHOD(thread_axil_pkt_cnt_tx_V_ap_vld);

    SC_METHOD(thread_axil_rx_timeElapse_V_ap_vld);

    SC_METHOD(thread_axil_rx_timestamp_sum_high_V);
    sensitive << ( rx_timestamp_sum_V );

    SC_METHOD(thread_axil_rx_timestamp_sum_high_V_ap_vld);

    SC_METHOD(thread_axil_rx_timestamp_sum_low_V);
    sensitive << ( rx_timestamp_sum_V );

    SC_METHOD(thread_axil_rx_timestamp_sum_low_V_ap_vld);

    SC_METHOD(thread_axil_tx_timeElapse_V_ap_vld);

    SC_METHOD(thread_axil_tx_timestamp_sum_high_V);
    sensitive << ( tx_timestamp_sum_V );

    SC_METHOD(thread_axil_tx_timestamp_sum_high_V_ap_vld);

    SC_METHOD(thread_axil_tx_timestamp_sum_low_V);
    sensitive << ( tx_timestamp_sum_V );

    SC_METHOD(thread_axil_tx_timestamp_sum_low_V_ap_vld);

    SC_METHOD(thread_rst_V);
    sensitive << ( axil_rst_V );

    SC_METHOD(thread_start_V);
    sensitive << ( axil_start_V );

    SC_METHOD(thread_transfer_length_V);
    sensitive << ( axil_len_low_V );
    sensitive << ( axil_len_high_V );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_virtual_clock.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sw_interface_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, start_V, "(port)start_V");
    sc_trace(mVcdFile, rst_V, "(port)rst_V");
    sc_trace(mVcdFile, transfer_length_V, "(port)transfer_length_V");
    sc_trace(mVcdFile, mismatch_V, "(port)mismatch_V");
    sc_trace(mVcdFile, tx_timeElapse_V, "(port)tx_timeElapse_V");
    sc_trace(mVcdFile, rx_timeElapse_V, "(port)rx_timeElapse_V");
    sc_trace(mVcdFile, tx_timestamp_sum_V, "(port)tx_timestamp_sum_V");
    sc_trace(mVcdFile, rx_timestamp_sum_V, "(port)rx_timestamp_sum_V");
    sc_trace(mVcdFile, pkt_cnt_tx_V, "(port)pkt_cnt_tx_V");
    sc_trace(mVcdFile, pkt_cnt_rx_V, "(port)pkt_cnt_rx_V");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, axil_start_V, "axil_start_V");
    sc_trace(mVcdFile, axil_rst_V, "axil_rst_V");
    sc_trace(mVcdFile, axil_len_low_V, "axil_len_low_V");
    sc_trace(mVcdFile, axil_len_high_V, "axil_len_high_V");
    sc_trace(mVcdFile, axil_mismatch_V, "axil_mismatch_V");
    sc_trace(mVcdFile, axil_mismatch_V_ap_vld, "axil_mismatch_V_ap_vld");
    sc_trace(mVcdFile, axil_tx_timeElapse_V_ap_vld, "axil_tx_timeElapse_V_ap_vld");
    sc_trace(mVcdFile, axil_rx_timeElapse_V_ap_vld, "axil_rx_timeElapse_V_ap_vld");
    sc_trace(mVcdFile, axil_tx_timestamp_sum_low_V, "axil_tx_timestamp_sum_low_V");
    sc_trace(mVcdFile, axil_tx_timestamp_sum_low_V_ap_vld, "axil_tx_timestamp_sum_low_V_ap_vld");
    sc_trace(mVcdFile, axil_tx_timestamp_sum_high_V, "axil_tx_timestamp_sum_high_V");
    sc_trace(mVcdFile, axil_tx_timestamp_sum_high_V_ap_vld, "axil_tx_timestamp_sum_high_V_ap_vld");
    sc_trace(mVcdFile, axil_rx_timestamp_sum_low_V, "axil_rx_timestamp_sum_low_V");
    sc_trace(mVcdFile, axil_rx_timestamp_sum_low_V_ap_vld, "axil_rx_timestamp_sum_low_V_ap_vld");
    sc_trace(mVcdFile, axil_rx_timestamp_sum_high_V, "axil_rx_timestamp_sum_high_V");
    sc_trace(mVcdFile, axil_rx_timestamp_sum_high_V_ap_vld, "axil_rx_timestamp_sum_high_V_ap_vld");
    sc_trace(mVcdFile, axil_pkt_cnt_tx_V_ap_vld, "axil_pkt_cnt_tx_V_ap_vld");
    sc_trace(mVcdFile, axil_pkt_cnt_rx_V_ap_vld, "axil_pkt_cnt_rx_V_ap_vld");
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
#endif

    }
    mHdltvinHandle.open("sw_interface.hdltvin.dat");
    mHdltvoutHandle.open("sw_interface.hdltvout.dat");
}

sw_interface::~sw_interface() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete sw_interface_AXILiteS_s_axi_U;
}

void sw_interface::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void sw_interface::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void sw_interface::thread_axil_mismatch_V() {
    axil_mismatch_V = esl_zext<32,1>(mismatch_V.read());
}

void sw_interface::thread_axil_mismatch_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        axil_mismatch_V_ap_vld = ap_const_logic_1;
    } else {
        axil_mismatch_V_ap_vld = ap_const_logic_0;
    }
}

void sw_interface::thread_axil_pkt_cnt_rx_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        axil_pkt_cnt_rx_V_ap_vld = ap_const_logic_1;
    } else {
        axil_pkt_cnt_rx_V_ap_vld = ap_const_logic_0;
    }
}

void sw_interface::thread_axil_pkt_cnt_tx_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        axil_pkt_cnt_tx_V_ap_vld = ap_const_logic_1;
    } else {
        axil_pkt_cnt_tx_V_ap_vld = ap_const_logic_0;
    }
}

void sw_interface::thread_axil_rx_timeElapse_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        axil_rx_timeElapse_V_ap_vld = ap_const_logic_1;
    } else {
        axil_rx_timeElapse_V_ap_vld = ap_const_logic_0;
    }
}

void sw_interface::thread_axil_rx_timestamp_sum_high_V() {
    axil_rx_timestamp_sum_high_V = rx_timestamp_sum_V.read().range(63, 32);
}

void sw_interface::thread_axil_rx_timestamp_sum_high_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        axil_rx_timestamp_sum_high_V_ap_vld = ap_const_logic_1;
    } else {
        axil_rx_timestamp_sum_high_V_ap_vld = ap_const_logic_0;
    }
}

void sw_interface::thread_axil_rx_timestamp_sum_low_V() {
    axil_rx_timestamp_sum_low_V = rx_timestamp_sum_V.read().range(32-1, 0);
}

void sw_interface::thread_axil_rx_timestamp_sum_low_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        axil_rx_timestamp_sum_low_V_ap_vld = ap_const_logic_1;
    } else {
        axil_rx_timestamp_sum_low_V_ap_vld = ap_const_logic_0;
    }
}

void sw_interface::thread_axil_tx_timeElapse_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        axil_tx_timeElapse_V_ap_vld = ap_const_logic_1;
    } else {
        axil_tx_timeElapse_V_ap_vld = ap_const_logic_0;
    }
}

void sw_interface::thread_axil_tx_timestamp_sum_high_V() {
    axil_tx_timestamp_sum_high_V = tx_timestamp_sum_V.read().range(63, 32);
}

void sw_interface::thread_axil_tx_timestamp_sum_high_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        axil_tx_timestamp_sum_high_V_ap_vld = ap_const_logic_1;
    } else {
        axil_tx_timestamp_sum_high_V_ap_vld = ap_const_logic_0;
    }
}

void sw_interface::thread_axil_tx_timestamp_sum_low_V() {
    axil_tx_timestamp_sum_low_V = tx_timestamp_sum_V.read().range(32-1, 0);
}

void sw_interface::thread_axil_tx_timestamp_sum_low_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        axil_tx_timestamp_sum_low_V_ap_vld = ap_const_logic_1;
    } else {
        axil_tx_timestamp_sum_low_V_ap_vld = ap_const_logic_0;
    }
}

void sw_interface::thread_rst_V() {
    rst_V = axil_rst_V.read();
}

void sw_interface::thread_start_V() {
    start_V = axil_start_V.read();
}

void sw_interface::thread_transfer_length_V() {
    transfer_length_V = esl_concat<32,32>(axil_len_high_V.read(), axil_len_low_V.read());
}

void sw_interface::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvoutHandle << mComma << "{"  <<  " \"start_V\" :  \"" << start_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"rst_V\" :  \"" << rst_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"transfer_length_V\" :  \"" << transfer_length_V.read() << "\" ";
        mHdltvinHandle << mComma << "{"  <<  " \"mismatch_V\" :  \"" << mismatch_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"tx_timeElapse_V\" :  \"" << tx_timeElapse_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"rx_timeElapse_V\" :  \"" << rx_timeElapse_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"tx_timestamp_sum_V\" :  \"" << tx_timestamp_sum_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"rx_timestamp_sum_V\" :  \"" << rx_timestamp_sum_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"pkt_cnt_tx_V\" :  \"" << pkt_cnt_tx_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"pkt_cnt_rx_V\" :  \"" << pkt_cnt_rx_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

